name: Minder apply from repo
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  install-rule-type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Fetch ID token
        run: |
          set -x -e
          echo $GITHUB_TOKEN
          URL="${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=minder"
          curl -o .action-token -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" $URL
          echo "MINDER_AUTH_TOKEN=$(jq -r .value <.action-token)" >> "$GITHUB_ENV"
      - uses: sigstore/cosign-installer@4959ce089c160fddf62f7b42464195ba1a56d382 # v3.6.0
      - uses: stacklok/minder-client-installer@0d4c5ed9a8dc6a2d152beeaf7b9cfb1fb5556dca # main
      - name: Apply Minder ruletypes
        env:
          MINDER_PROJECT: 14ac1534-e81a-4060-b4b8-bff2f1ee076a
          # Very temporary!  My ngrok endpoint
          MINDER_GRPC_SERVER_PORT: 13401
          MINDER_GRPC_SERVER_HOST: 0.tcp.us-cal-1.ngrok.io
          MINDER_GRPC_SERVER_INSECURE: true
        run: |
          minder ruletype apply -f ./rule-types
          # Minder ruletype apply takes a directory, but profile apply does not!!
          minder profile apply -f ./profiles/enable-auto-apply.yaml
