name: Check id token
on: workflow_dispatch

permissions:
  id-token: write

jobs:
  check_id_token:
    runs-on: ubuntu-latest
    steps:
      - name: Check id token
        run: |
          set -x -e
          echo $GITHUB_TOKEN
          URL="${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=api%3A%2F%2Fdefault"
          curl -o .action-token -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" $URL
          jq -r .value <.action-token > .action-token-value
          tr '.' '\n' <.action-token-value | sed 's/eyJ/EYj/'