name: Check id token
on: workflow_dispatch

permissions:
  id-token: write

jobs:
  check_id_token:
    runs-on: ubuntu-latest
    steps:
      - name: Check id token
        run: |
          set -x -e
          echo $GITHUB_TOKEN
          echo $ACTIONS_ID_TOKEN_REQUEST_URL
          echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN
          URL="${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=api%3A%2F%2Fdefault"
          echo $URL
          curl -v -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" $URL